# Generated by Django 2.2.5 on 2019-09-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('nick', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nr_of_rounds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster', models.TextField()),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AoS_app.Army')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AoS_app.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AoS_app.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nr', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AoS_app.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_points', models.IntegerField(null=True)),
                ('scenario_points', models.IntegerField(null=True)),
                ('agenda', models.BooleanField()),
                ('victory_points', models.IntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AoS_app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField()),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_1', to='AoS_app.GamePlayer')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_2', to='AoS_app.GamePlayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AoS_app.Round')),
            ],
        ),
    ]
