# Generated by Django 2.2.5 on 2019-09-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AoS_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(through='AoS_app.TournamentPlayer', to='AoS_app.Player'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='army',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AoS_app.Army'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='roster',
            field=models.TextField(null=True),
        ),
    ]
