# Generated by Django 2.2.5 on 2019-09-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoS_app', '0003_auto_20190904_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='agenda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='kill_points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='scenario_points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='victory_points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
