# Generated by Django 2.2.5 on 2019-09-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoS_app', '0004_auto_20190905_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='kill_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='victory_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
