# Generated by Django 2.2.5 on 2019-09-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AoS_app', '0006_auto_20190905_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='kill_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='victory_points',
            field=models.IntegerField(default=0),
        ),
    ]
